apiVersion: apps/v1
kind: Deployment
metadata:
  name: drs-api
  namespace: drs
spec:
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: drs-api
  template:
    metadata:
      labels:
        app: drs-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: drs-api
        image: ghcr.io/ase-group-11/drs-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: drs-secrets
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drs-consumer
  namespace: drs
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: drs-consumer
  template:
    metadata:
      labels:
        app: drs-consumer
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: drs-consumer
        image: ghcr.io/ase-group-11/drs-backend:latest
        imagePullPolicy: Always
        command: ["python", "-m", "app.consumers.notification_consumer"]
        envFrom:
        - secretRef:
            name: drs-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: drs-api
  namespace: drs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drs-api
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: drs-consumer
  namespace: drs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drs-consumer
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70