"""Add User and Disaster models with PostGIS support

Revision ID: 08043ae77acb
Revises: 
Create Date: 2026-02-02 23:03:02.861544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '08043ae77acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'ERT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('disasters',
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lng', sa.Float(), nullable=False),
    sa.Column('disaster_type', sa.Enum('FLOOD', 'FIRE', 'ACCIDENT', 'MEDICAL', 'OTHER', name='disastertype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='disasterseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='disasterstatus'), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disaster_id')
    )
    # Note: PostGIS automatically creates spatial index for Geography columns
    # op.create_index('idx_disasters_location', 'disasters', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_disasters_created_at'), 'disasters', ['created_at'], unique=False)
    op.create_index(op.f('ix_disasters_disaster_id'), 'disasters', ['disaster_id'], unique=False)
    op.create_index(op.f('ix_disasters_disaster_type'), 'disasters', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_disasters_location_lat'), 'disasters', ['location_lat'], unique=False)
    op.create_index(op.f('ix_disasters_location_lng'), 'disasters', ['location_lng'], unique=False)
    op.create_index(op.f('ix_disasters_severity'), 'disasters', ['severity'], unique=False)
    op.create_index(op.f('ix_disasters_status'), 'disasters', ['status'], unique=False)
    # Note: spatial_ref_sys is created by PostGIS extension, so we don't drop it
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_disasters_status'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_severity'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_location_lng'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_location_lat'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_disaster_type'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_disaster_id'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_created_at'), table_name='disasters')
    op.drop_index('idx_disasters_location', table_name='disasters', postgresql_using='gist')
    op.drop_table('disasters')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
