"""Initial schema

Revision ID: 387605b8a1e4
Revises: 
Create Date: 2026-01-26 19:22:13.139086
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387605b8a1e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_teams',
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='emergency_team_role'), nullable=False),
    sa.Column('department', sa.Enum('MEDICAL', 'POLICE', 'FIRE', 'IT', name='department'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED', name='user_status'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_dept_status', 'emergency_teams', ['department', 'status'], unique=False)
    op.create_index('idx_team_phone_status', 'emergency_teams', ['phone_number', 'status'], unique=False)
    op.create_index('idx_team_role_dept', 'emergency_teams', ['role', 'department'], unique=False)
    op.create_index(op.f('ix_emergency_teams_department'), 'emergency_teams', ['department'], unique=False)
    op.create_index(op.f('ix_emergency_teams_email'), 'emergency_teams', ['email'], unique=True)
    op.create_index(op.f('ix_emergency_teams_employee_id'), 'emergency_teams', ['employee_id'], unique=True)
    op.create_index(op.f('ix_emergency_teams_id'), 'emergency_teams', ['id'], unique=True)
    op.create_index(op.f('ix_emergency_teams_phone_number'), 'emergency_teams', ['phone_number'], unique=True)
    op.create_index(op.f('ix_emergency_teams_role'), 'emergency_teams', ['role'], unique=False)
    op.create_index(op.f('ix_emergency_teams_status'), 'emergency_teams', ['status'], unique=False)
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED', name='user_status'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_phone_status', 'users', ['phone_number', 'status'], unique=False)
    op.create_index('idx_user_status_created', 'users', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_status_created', table_name='users')
    op.drop_index('idx_user_phone_status', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_emergency_teams_status'), table_name='emergency_teams')
    op.drop_index(op.f('ix_emergency_teams_role'), table_name='emergency_teams')
    op.drop_index(op.f('ix_emergency_teams_phone_number'), table_name='emergency_teams')
    op.drop_index(op.f('ix_emergency_teams_id'), table_name='emergency_teams')
    op.drop_index(op.f('ix_emergency_teams_employee_id'), table_name='emergency_teams')
    op.drop_index(op.f('ix_emergency_teams_email'), table_name='emergency_teams')
    op.drop_index(op.f('ix_emergency_teams_department'), table_name='emergency_teams')
    op.drop_index('idx_team_role_dept', table_name='emergency_teams')
    op.drop_index('idx_team_phone_status', table_name='emergency_teams')
    op.drop_index('idx_team_dept_status', table_name='emergency_teams')
    op.drop_table('emergency_teams')
    # ### end Alembic commands ###
