"""added reference id to photos table

Revision ID: 464c978e238b
Revises: 3bf1bc535733
Create Date: 2026-02-18 16:35:10.961439
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '464c978e238b'
down_revision = '3bf1bc535733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('disaster_photos', sa.Column('reference_id', sa.String(length=50), nullable=False, comment='Grouping reference; can be any uuid if thats a preference.'))
    op.create_index(op.f('ix_disaster_photos_reference_id'), 'disaster_photos', ['reference_id'], unique=False)
    op.alter_column('disasters', 'disaster_status',
               existing_type=postgresql.ENUM('ACTIVE', 'MONITORING', 'RESOLVED', 'ARCHIVED', name='disaster_status'),
               server_default=None,
               existing_comment='Disaster lifecycle: ACTIVE/MONITORING/RESOLVED/ARCHIVED',
               existing_nullable=False)
    op.alter_column('disasters', 'people_affected',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Official count of people affected',
               existing_nullable=False)
    op.alter_column('disasters', 'multiple_casualties',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Official: Multiple casualties confirmed',
               existing_nullable=False)
    op.alter_column('disasters', 'structural_damage',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Official: Structural damage confirmed',
               existing_nullable=False)
    op.alter_column('disasters', 'road_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Official: Road access blocked',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disasters', 'road_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Official: Road access blocked',
               existing_nullable=False)
    op.alter_column('disasters', 'structural_damage',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Official: Structural damage confirmed',
               existing_nullable=False)
    op.alter_column('disasters', 'multiple_casualties',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Official: Multiple casualties confirmed',
               existing_nullable=False)
    op.alter_column('disasters', 'people_affected',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Official count of people affected',
               existing_nullable=False)
    op.alter_column('disasters', 'disaster_status',
               existing_type=postgresql.ENUM('ACTIVE', 'MONITORING', 'RESOLVED', 'ARCHIVED', name='disaster_status'),
               server_default=sa.text("'ACTIVE'::disaster_status"),
               existing_comment='Disaster lifecycle: ACTIVE/MONITORING/RESOLVED/ARCHIVED',
               existing_nullable=False)
    op.drop_index(op.f('ix_disaster_photos_reference_id'), table_name='disaster_photos')
    op.drop_column('disaster_photos', 'reference_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
